name: pod_player
description: Vimeo and youtube player for flutter, Pod player provides customizable video player controls that support android, ios and web.
version: 0.3.2
homepage: https://github.com/newtaDev/pod_player

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  http: ^1.2.2
  get: ^4.6.6
  wakelock_plus: ^1.2.8
  universal_html: ^2.2.4
  youtube_explode_dart:
    git:
      url: https://github.com/Hexer10/youtube_explode_dart.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

screenshots:
  - description: Pod video player logo
    path: screenshots/logo.png
